# Z-Score normalization

In [1]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# 假設有一個數據集
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 創建 StandardScaler 物件
scaler = StandardScaler()

# 使用 fit_transform 進行標準化
X_scaled = scaler.fit_transform(X)

print("標準化後的數據：")
print(X_scaled)

標準化後的數據：
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


# Min-Max Normalization

In [2]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 假設有一個數據集
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 創建 MinMaxScaler 物件
scaler = MinMaxScaler()

# 使用 fit_transform 進行縮放
X_scaled = scaler.fit_transform(X)

print("縮放後的數據：")
print(X_scaled)

縮放後的數據：
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


# Natural Log Transformation

In [3]:
import numpy as np

# 假設有一個數據集
X = np.array([1, 10, 100, 1000, 10000])

# 使用自然對數轉換
X_log = np.log(X)

print("自然對數轉換後的數據：")
print(X_log)

自然對數轉換後的數據：
[0.         2.30258509 4.60517019 6.90775528 9.21034037]
