In [1]:
import numpy as np

# 建立 3x3 矩陣
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 建立另一個矩陣
B = np.eye(3)  # 3x3 單位矩陣

# 做矩陣相乘
C = A @ B

print("矩陣 A:")
print(A)
print("\n矩陣 B (單位矩陣):")
print(B)
print("\nA @ B =")
print(C)



矩陣 A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

矩陣 B (單位矩陣):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A @ B =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [2]:
# 測試 numpy 版本
print("\nnumpy version:", np.__version__)


numpy version: 2.3.5
