# Numpy command

In [1]:
# import numpy
import numpy as np
# 建立ndarray物件
ndarr = np.array([3, 4, -5])

print(ndarr)
print(ndarr.size)
print(ndarr.dtype)

[ 3  4 -5]
3
int64


# 建立一維陣列

In [2]:
np.array([3,4,5])
np.empty(3)
np.zeros(3)
np.ones(3)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 建立二維陣列

In [3]:
np.array(
    [
        [1,2],
        [3,4],
        [5,6]
    ]
        )

array([[1, 2],
       [3, 4],
       [5, 6]])

# 建立三維陣列

In [4]:
array_3d = np.array([[[1, 2, 3, 4], 
                      [5, 6, 7, 8], 
                      [9, 10, 11, 12]],
                     
                     [[13, 14, 15, 16], 
                      [17, 18, 19, 20], 
                      [21, 22, 23, 24]]])
print(array_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


# 建立多維陣列

In [5]:
# 創建一個四維陣列，形狀為 1x1x1x2
array_4d = np.array([[[[1, 2]]]])

# 逐元運算

In [6]:
data1 = np.array([3,4])
data2 = np.array([5,8])

data1 + data2
data1 - data2
data1 * data2
data1 / data2
data1 > data2
data1 == data2
data1 <= data2

array([ True,  True])

# 矩陣運算

In [7]:
data3 = np.array([
    [2,1]
])
data4 = np.array([
    [4,7,8],[3,5,7]
])

data3.dot(data4)  # 內積
data3@data4       # 內積
np.outer(data3,data4)  # 外積

array([[ 8, 14, 16,  6, 10, 14],
       [ 4,  7,  8,  3,  5,  7]])

# 統計

In [8]:
data4.sum()
data4.sum(axis=0)  # 加總column
data4.sum(axis=1)  # 加總row
data4.min()
data4.cumsum()  # 逐值累加
data4.mean()
data4.std()    # 標準差

1.7950549357115015

# 形狀

In [9]:
data4.shape

(2, 3)

In [10]:
# 轉置
data4.T.shape

(3, 2)

In [11]:
# 扁平化
data4.ravel()

array([4, 7, 8, 3, 5, 7])

In [12]:
# 重塑資料形狀
data4.reshape(3,2)
data4.reshape(2,3)

new_data = np.ones(18).reshape(2,3,3)
print(new_data)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


# 索引

In [13]:
data1[1]
data4[1,2]

7

# 切片

In [14]:
# 多維陣列[開始：結束] (不包含結束)
data1[0:1]
data4[0:2, 0:1]

array([[4],
       [3]])

In [15]:
data4[0,...]
data4[...,0:1]

array([[4],
       [3]])

# 合併

In [16]:
arr1 = np.zeros(4).reshape(2,2)
arr2 = np.ones(4).reshape(2,2)

# 合併第一個維度
np.vstack((arr1,arr2))

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [17]:
# 合併第二個維度
np.hstack((arr1,arr2))

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

# 切割

In [18]:
arr3=np.array([
    [1,2,3,4],
    [5,6,7,8]
])

np.vsplit(arr3, 2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [19]:
np.hsplit(arr3, 2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

# 亂數

In [20]:
j = np.random.rand(10)
j

array([0.37533631, 0.29233192, 0.33570952, 0.0977689 , 0.88881474,
       0.46621645, 0.19321183, 0.76027766, 0.61960783, 0.73008314])

In [28]:
i = np.random.rand(10).reshape(2,5)
print(i)
print(i.shape)

[[0.65621582 0.85930741 0.47603063 0.28234471 0.37231419]
 [0.48275733 0.64801167 0.06148787 0.18000616 0.55398277]]
(2, 5)


In [ ]:
q = np.random.randint(1,20,100)
q


array([ 5, 12, 11,  7,  5, 14, 10, 19,  2, 17, 18, 17,  7, 13,  6, 17,  4,
       12,  6, 14, 10,  3,  4,  6, 11,  7,  2, 19,  4, 17, 15,  8, 15,  1,
       15,  7,  3,  7,  1,  3, 19, 17,  6, 15,  1, 14,  9,  4, 14, 17,  4,
        8, 13,  7,  8, 18,  8, 14,  4, 12,  7, 13,  1, 15,  1, 17,  8, 12,
       12,  6, 13, 17,  5, 15, 15, 10,  9,  6, 10,  7, 11, 13, 16,  1,  8,
        7, 19, 10,  3, 15, 18,  9,  1,  3, 15, 15, 11, 13, 18,  4])